#!/bin/sh
echo "Performing helm lint before push..."
lint_output=$(helm lint IITS_CHART_NAME)
lint_command=$(helm lint IITS_CHART_NAME)
lint_command_status=$?

if [ $lint_command_status -eq 0 ]; then
  echo "Helm lint completed successfully. You can push."
  exit 0
else
  echo "Helm lint failed. Please fix your Helm chart."
  echo "$lint_output"
  exit 1
fi
