name: "iits-argo-charts-updater"
version: "0.1.3"
usage: "Go into the Argo App of Apps Helm Chart and execute helm iits-argo-charts-updater"
description: |-
  "Go into the Argo App of Apps Helm Chart and execute helm iits-argo-charts-updater"
command: "$HELM_PLUGIN_DIR/run.sh"